FROM python:3.12-slim

WORKDIR /Server

COPY MilesmartServer MilesmartServer
COPY ui ui
COPY requirements.txt .
COPY client_secret.json client_secret.json
COPY main.py .

RUN pip3 install -r requirements.txt

EXPOSE 5000

CMD [ "python3", "main.py"]